# Generated by Django 5.0.2 on 2024-02-23 16:26

from django.db import migrations, models

def create_groups(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_announce = Permission.objects.get(codename='add_announce')
    change_announce = Permission.objects.get(codename='change_announce')
    delete_announce = Permission.objects.get(codename='delete_announce')
    view_announce = Permission.objects.get(codename='view_announce')
    
    annonceurs_permissions = [
        add_announce,
        change_announce,
        delete_announce,
        view_announce,
    ]
    
    annonceurs = Group(name='annonceurs')
    annonceurs.save()
    annonceurs.permissions.set(annonceurs_permissions)

    clients = Group(name='clients')
    clients.save()
    clients.permissions.add(view_announce)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
